# cargo_reg_local/Makefile.toml
# https://github.com/sagiegurari/cargo-make/blob/master/src/lib/Makefile.stable.toml

[config]
skip_core_tasks = true

#region: public callable tasks/flows

    [tasks.default]
    description = "show list of public callable tasks"
    clear = true
    command = "cargo"
    args = ["make","--list-all-steps"]

    [tasks.dev]
    description = "cargo build development"
    clear=true
    dependencies = [
        "lmake_version_from_date",
        "build_dev",
        "post_build_dev",
    ]

    [tasks.release]
    description = "cargo build release"
    clear=true
    dependencies = [
        "lmake_version_from_date",
        "build_release",
        "post_build_release",
    ]

    [tasks.audit]
    description = "cargo audit - for warning dependencies"
    clear = true
    dependencies = [
        "cargo_audit",
    ]
    
    [tasks.fmt]
    description = "cargo fmt - format code"
    clear = true
    dependencies = [
        "cargo_fmt",
    ]

    [tasks.doc]
    description = "call cargo doc"
    clear=true
    dependencies = [
        "insert_readme",
        "cargo_doc",
        "cargo_docs_copy",
    ]

#endregion

#why is task "empty" in the list of public tasks?

[tasks.build_dev]
clear=true
private=true
command = "cargo"
args = ["build"]

[tasks.build_release]
clear=true
private=true
command = "cargo"
args = ["build","--release"]

[tasks.post_build_dev]
clear=true
private=true
script = [
    "echo Use this example how to run it. Just copy/paste. And modify the argument:   target/debug/cargo_reg_local thread"
]

[tasks.post_build_release]
clear=true
private=true
script = [
    "echo Use this example how to run it. Just copy/paste. And modify the argument:   target/release/cargo_reg_local thread"
]

[tasks.cargo_audit]
description = "cargo audit"
clear = true
private = true
command = "cargo"
args = ["audit"]

[tasks.cargo_fmt]
description = "cargo fmt"
clear = true
private = true
command = "cargo"
args = ["fmt"]

[tasks.insert_readme]
description = "copy the content of readme.md into *.rs comments (for the docs)"
clear = true
private = true
script= ["lmake_readme"]

[tasks.cargo_doc]
description = "call cargo doc"
clear = true
private = true
command="cargo"
args=["doc","--no-deps","--document-private-items"]

[tasks.lmake_version_from_date]
description = "in cargo.toml change version to today date"
clear = true
private = true
script= ["lmake_version_from_date"]

[tasks.cargo_docs_copy]
description = "copy folder `/target/doc` to /docs folder (github standard)"
workspace=false
clear = true
private = false
script = [
    "\\rsync -avz --delete-after target/doc/*  docs/",
]

